name: hello_nitr
description: "A contact sharing app for NIT Rourkela official use."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 2.0.0 
# Breaking, Feature, Fix, Build example: 2.0.0+1
# The version number should follow the semantic versioning format,
# which consists of three numbers separated by dots (major.minor.patch), 
# and an optional build number separated by a plus sign (+).
# Major version number should be incremented for incompatible changes.
# Minor version number should be incremented for backward-compatible changes.
# Patch version number should be incremented for backward-compatible bug fixes.
# Build number should be incremented for backward-compatible changes in the build process (e.g. changing the build number format).


environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  http: ^1.2.1
  package_info_plus: ^8.0.0
  logging: ^1.2.0
  sqflite: ^2.3.3+1
  flutter_secure_storage: ^9.2.2
  path: ^1.9.0
  simnumber: ^0.0.12
  flutter_udid: ^3.0.0
  pinput: ^5.0.0
  loading_animation_widget: ^1.2.1
  local_auth: ^2.2.0
  font_awesome_flutter: ^10.7.0
  share_plus: ^9.0.0
  infinite_scroll_pagination: ^4.0.0
  image: ^4.2.0
  flutter_cache_manager: ^3.3.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.3.9
  otp: ^3.1.4
  flag: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/hello_nitr.png
    - assets/images/error/error_illustration.png
    - assets/images/login-main-image.png
